development:
  adapter:  postgresql
  database: parsedev
  host:     localhost
  port:     5432
  username: Petr
  password: 123456
  pool:     5         #????
  timeout:  5000      #????

test:
  adapter: postgresql
  database: parsetest
  host:     localhost
  port:     5432
  username: admin_test
  password: 123456
  pool:     5         #????
  timeout:  5000      #????
